-- Sprintiverse V2 Phase 1 core schema
create extension if not exists pgcrypto;
create type public.workspace_role as enum ('owner','agent');
create type public.subscription_status as enum ('none','trialing','trial_expired','pending','active','past_due','canceled');
create type public.ticket_status as enum ('open','pending','resolved','closed');
create type public.ticket_priority as enum ('low','normal','high','urgent');
create type public.message_author as enum ('customer','agent','system');
create type public.invitation_status as enum ('pending','accepted','revoked');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, avatar_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null check (char_length(trim(name)) between 2 and 80), owner_id uuid not null references auth.users(id) on delete cascade, plan text check(plan in('starter','growth','pro')), billing_cycle text check(billing_cycle in('monthly','yearly')), currency text check(currency in('INR','USD')), subscription_status public.subscription_status not null default 'none', trial_started_at timestamptz, trial_ends_at timestamptz, razorpay_customer_id text, razorpay_subscription_id text, current_period_end timestamptz, sample_data_seeded_at timestamptz, onboarding_completed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.workspace_members (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.workspace_role not null default 'agent', created_at timestamptz default now(), unique(workspace_id,user_id));
create table public.workspace_invitations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, email text not null, role public.workspace_role not null default 'agent', status public.invitation_status not null default 'pending', token text not null unique default encode(gen_random_bytes(24),'hex'), invited_by uuid not null references auth.users(id) on delete cascade, created_at timestamptz default now(), expires_at timestamptz not null default now()+interval '14 days', accepted_at timestamptz, accepted_by uuid references auth.users(id) on delete set null);
create table public.customers (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, name text not null, email text not null, company text, is_sample boolean not null default false, created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,email));
create sequence public.ticket_number_seq;
create table public.tickets (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, customer_id uuid references public.customers(id) on delete set null, number bigint not null default nextval('public.ticket_number_seq'), subject text not null, status public.ticket_status not null default 'open', priority public.ticket_priority not null default 'normal', channel text not null default 'email', assignee_id uuid references auth.users(id) on delete set null, is_sample boolean not null default false, last_activity_at timestamptz default now(), resolved_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.ticket_messages (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, ticket_id uuid not null references public.tickets(id) on delete cascade, author_type public.message_author not null, author_id uuid references auth.users(id) on delete set null, author_name text not null, body text not null, is_internal boolean not null default false, is_sample boolean not null default false, created_at timestamptz default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email,avatar_url) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),nullif(new.raw_user_meta_data->>'name',''),split_part(coalesce(new.email,''),'@',1)),new.email,nullif(new.raw_user_meta_data->>'avatar_url','')) on conflict(id) do update set email=excluded.email; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.is_workspace_member(w uuid,u uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.workspace_members where workspace_id=w and user_id=u); $$;
create or replace function public.is_workspace_owner(w uuid,u uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.workspace_members where workspace_id=w and user_id=u and role='owner'); $$;
create or replace function public.create_workspace_with_owner(workspace_name text, selected_plan text default null, selected_cycle text default null, selected_currency text default 'INR') returns uuid language plpgsql security definer set search_path=public as $$ declare wid uuid; begin if auth.uid() is null then raise exception 'not authenticated'; end if; insert into public.workspaces(name,owner_id,plan,billing_cycle,currency) values(trim(workspace_name),auth.uid(),selected_plan,selected_cycle,selected_currency) returning id into wid; insert into public.workspace_members(workspace_id,user_id,role) values(wid,auth.uid(),'owner'); return wid; end; $$;
create or replace function public.start_workspace_trial(w uuid) returns public.workspaces language plpgsql security definer set search_path=public as $$ declare r public.workspaces; begin if not public.is_workspace_owner(w,auth.uid()) then raise exception 'not authorized'; end if; update public.workspaces set subscription_status='trialing',trial_started_at=coalesce(trial_started_at,now()),trial_ends_at=coalesce(trial_ends_at,now()+interval '24 hours') where id=w returning * into r; return r; end; $$;
create or replace function public.seed_sample_data(w uuid) returns void language plpgsql security definer set search_path=public as $$ declare c1 uuid;c2 uuid;t1 uuid;t2 uuid; begin if not public.is_workspace_member(w,auth.uid()) then raise exception 'not authorized'; end if; if exists(select 1 from public.customers where workspace_id=w and is_sample) then return; end if; insert into public.customers(workspace_id,name,email,company,is_sample) values(w,'Aarav Mehta','aarav@example.com','Northstar Labs',true) returning id into c1; insert into public.customers(workspace_id,name,email,company,is_sample) values(w,'Emily Carter','emily@example.com','Acme Commerce',true) returning id into c2; insert into public.tickets(workspace_id,customer_id,subject,status,priority,channel,is_sample) values(w,c1,'Question about my latest invoice','open','high','email',true) returning id into t1; insert into public.tickets(workspace_id,customer_id,subject,status,priority,channel,is_sample) values(w,c2,'Unable to update account details','pending','normal','email',true) returning id into t2; insert into public.ticket_messages(workspace_id,ticket_id,author_type,author_name,body,is_sample) values(w,t1,'customer','Aarav Mehta','Hi team, I have a question about the amount on my latest invoice.',true),(w,t2,'customer','Emily Carter','I am getting an error when I try to update my account details.',true); update public.workspaces set sample_data_seeded_at=now() where id=w; end; $$;
create or replace function public.accept_workspace_invitation(invite_token text) returns uuid language plpgsql security definer set search_path=public as $$ declare inv public.workspace_invitations; wid uuid; begin if auth.uid() is null then raise exception 'not authenticated'; end if; select * into inv from public.workspace_invitations where token=invite_token and status='pending' and expires_at>now() for update; if not found then raise exception 'invitation is invalid or expired'; end if; if lower(inv.email) <> lower(coalesce((select email from auth.users where id=auth.uid()),'')) then raise exception 'invitation email does not match signed-in account'; end if; wid:=inv.workspace_id; insert into public.workspace_members(workspace_id,user_id,role) values(wid,auth.uid(),inv.role) on conflict(workspace_id,user_id) do update set role=excluded.role; update public.workspace_invitations set status='accepted',accepted_at=now(),accepted_by=auth.uid() where id=inv.id; return wid; end; $$;
create or replace function public.enforce_trial_state(w uuid) returns public.subscription_status language plpgsql security definer set search_path=public as $$ declare s public.subscription_status; e timestamptz; begin if not public.is_workspace_member(w,auth.uid()) then raise exception 'not authorized'; end if; select subscription_status,trial_ends_at into s,e from public.workspaces where id=w; if s='trialing' and e is not null and e<=now() then update public.workspaces set subscription_status='trial_expired' where id=w returning subscription_status into s; end if; return s; end; $$;

grant execute on function public.create_workspace_with_owner(text,text,text,text) to authenticated;
grant execute on function public.start_workspace_trial(uuid) to authenticated;
grant execute on function public.seed_sample_data(uuid) to authenticated;
grant execute on function public.accept_workspace_invitation(text) to authenticated;
grant execute on function public.enforce_trial_state(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.workspace_invitations enable row level security;
alter table public.customers enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;
create policy profiles_self on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy workspaces_member_select on public.workspaces for select to authenticated using(public.is_workspace_member(id,auth.uid()));
create policy workspaces_owner_update on public.workspaces for update to authenticated using(public.is_workspace_owner(id,auth.uid())) with check(public.is_workspace_owner(id,auth.uid()));
create policy members_same_workspace_select on public.workspace_members for select to authenticated using(public.is_workspace_member(workspace_id,auth.uid()));
create policy members_owner_manage on public.workspace_members for all to authenticated using(public.is_workspace_owner(workspace_id,auth.uid())) with check(public.is_workspace_owner(workspace_id,auth.uid()));
create policy invitations_owner_select on public.workspace_invitations for select to authenticated using(public.is_workspace_owner(workspace_id,auth.uid()));
create policy invitations_owner_insert on public.workspace_invitations for insert to authenticated with check(public.is_workspace_owner(workspace_id,auth.uid()) and invited_by=auth.uid());
create policy invitations_owner_update on public.workspace_invitations for update to authenticated using(public.is_workspace_owner(workspace_id,auth.uid())) with check(public.is_workspace_owner(workspace_id,auth.uid()));
create policy invitations_owner_delete on public.workspace_invitations for delete to authenticated using(public.is_workspace_owner(workspace_id,auth.uid()));
create policy customers_workspace on public.customers for all to authenticated using(public.is_workspace_member(workspace_id,auth.uid())) with check(public.is_workspace_member(workspace_id,auth.uid()));
create policy tickets_workspace on public.tickets for all to authenticated using(public.is_workspace_member(workspace_id,auth.uid())) with check(public.is_workspace_member(workspace_id,auth.uid()));
create policy messages_workspace on public.ticket_messages for all to authenticated using(public.is_workspace_member(workspace_id,auth.uid())) with check(public.is_workspace_member(workspace_id,auth.uid()));

create index if not exists idx_workspace_members_user on public.workspace_members(user_id);
create index if not exists idx_tickets_workspace_activity on public.tickets(workspace_id,last_activity_at desc);
create index if not exists idx_messages_ticket_created on public.ticket_messages(ticket_id,created_at);
create index if not exists idx_invitations_token on public.workspace_invitations(token);
